### ISSUE TITLE
Update Beta 1-3-1   to 1-3-2

### ISSUE THREAD

**Issue by MichaRGXDesign** [pro2store/Pro2Store#34]
SQL mistake

Warnung
JInstaller: :Install: SQL-Fehler You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `amount` int NULL COMMENT ''' at line 1
Erweiterung „Aktualisierung“: SQL Fehler beim Ausführen der Abfrage: „DB-Funktion mit Fehlercode 1064 fehlgeschlagen!
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `amount` int NULL COMMENT ''' at line 1
SQL =
ALTER TABLE `#__protostore_order_products` ADD COLUMN IF NOT EXISTS `amount` int NULL COMMENT '';
“
Paket Aktualisierung: Bei der Installation der Erweiterung trat ein Fehler auf: com_protostore.zip

**Comment by pro2store** [comment]
Hi Micha,

Thanks for reporting.

This has now been fixed in BETA 5.

Thank you again! :)
